apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:hashtagf/argo-demo.git
    targetRevision: main
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
